spring.datasource.url=jdbc:mysql://localhost:3306/voting_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Frumusica4414
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

# Pune aici token-ul tau de la https://dashboard.ngrok.com/get-started/your-authtoken
# Daca il lasi gol, ngrok merge dar cu limitari (conexiuni scurte, URL schimbat la restart)
ngrok.authtoken=3BubWqzqRNFt81USvF0Hfs4lccE_ts6r42cH9NAseEk6jMLp