spring.datasource.url=jdbc:h2:mem:voting_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

server.port=8080

# Ngrok token
ngrok.authtoken=3BubWqzqRNFt81USvF0Hfs4lccE_ts6r42cH9NAseEk6jMLp